name: user_microservice
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  json_annotation: ^4.0.0
#   path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0
  build_runner: ^2.0.0
  json_serializable: ^4.0.0
  test: ^1.16.0
